version: "3.9"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - "5510:5432"
    api:
        build:
          context: .
          dockerfile: api.Dockerfile
        environment:
            DOTNET_ENVIRONMENT: "Development"
            ConnectionStrings__Adviser: "User ID=postgres;Password=example;Host=db;Port=5432;Database=Prodinstock;Pooling=true"
        ports:
            - "5500:80"
            - "5501:443"
        depends_on:
            - db